export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="mb-2 text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mb-8 text-sm text-gray-500">Last updated: April 20, 2026</p>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
        <section>
          <h2 className="text-xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
          <p>By accessing or using CleanCheck ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">2. Description of Service</h2>
          <p>CleanCheck is a quality control documentation platform for cleaning businesses. The Service allows users to document inspections with photos, generate AI-powered reports, and deliver those reports to clients.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">3. Account Registration</h2>
          <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must provide accurate and complete information when registering.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">4. Subscription and Payment</h2>
          <p>CleanCheck offers paid subscription plans. By subscribing, you agree to pay the applicable fees. Subscriptions renew automatically unless cancelled. You may cancel at any time through your account settings. Refunds are issued at our discretion for unused subscription periods.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">5. Free Trial</h2>
          <p>We offer a 14-day free trial. No credit card is required to start a trial. At the end of the trial period, you must subscribe to continue using the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="ml-6 list-disc space-y-1">
            <li>Use the Service for any unlawful purpose</li>
            <li>Upload content that is illegal, harmful, or violates third-party rights</li>
            <li>Attempt to gain unauthorized access to any part of the Service</li>
            <li>Interfere with or disrupt the integrity of the Service</li>
            <li>Resell or sublicense the Service without written permission</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">7. Your Content</h2>
          <p>You retain ownership of all content you upload to CleanCheck (photos, notes, reports). By uploading content, you grant us a limited license to store and process it solely to provide the Service to you.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">8. AI-Generated Reports</h2>
          <p>Reports generated by our AI are provided as-is for informational purposes. You are responsible for reviewing reports before sending them to clients. CleanCheck is not liable for inaccuracies in AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">9. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, CleanCheck shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">10. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or meet your specific requirements.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">11. Termination</h2>
          <p>We may suspend or terminate your account if you violate these Terms. You may delete your account at any time. Upon termination, your data will be retained for 30 days then permanently deleted.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">12. Changes to Terms</h2>
          <p>We may modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">13. Governing Law</h2>
          <p>These Terms are governed by the laws of the United States. Any disputes shall be resolved through binding arbitration.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">14. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:josh@cleancheck.io" className="text-blue-600 hover:underline">josh@cleancheck.io</a>.</p>
        </section>
      </div>
    </div>
  )
}
