import { createClient } from '@/lib/supabase/server'
import { NextRequest } from 'next/server'
import { randomUUID } from 'crypto'

export async function POST(request: NextRequest) {
  const { inspectionId } = await request.json()
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: inspection } = await supabase
    .from('inspections')
    .select('*, properties(name, address, client_email)')
    .eq('id', inspectionId)
    .single()

  if (!inspection?.properties?.client_email) {
    return Response.json({ error: 'No client email' }, { status: 400 })
  }

  // Generate share token if not already set
  let token = inspection.share_token
  if (!token) {
    token = randomUUID()
    await supabase.from('inspections').update({ share_token: token }).eq('id', inspectionId)
  }

  const property = inspection.properties as any
  const reportUrl = `${process.env.NEXT_PUBLIC_APP_URL}/report/${token}`
  const score = inspection.overall_score
  const scoreColor = score >= 80 ? '#22c55e' : score >= 60 ? '#eab308' : '#ef4444'

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0f1117;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f1117;padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr><td style="background:#161b27;border-radius:12px 12px 0 0;border:1px solid rgba(255,255,255,0.1);border-bottom:none;padding:24px 32px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td style="color:#60a5fa;font-size:18px;font-weight:700;">✓ CleanCheck</td>
              <td align="right" style="color:#6b7280;font-size:13px;">Quality Report</td>
            </tr>
          </table>
        </td></tr>

        <!-- Body -->
        <tr><td style="background:#161b27;border:1px solid rgba(255,255,255,0.1);border-top:none;border-bottom:none;padding:32px;">

          <h1 style="margin:0 0 4px;color:#ffffff;font-size:24px;font-weight:700;">${property?.name ?? 'Inspection Complete'}</h1>
          ${property?.address ? `<p style="margin:0 0 24px;color:#6b7280;font-size:14px;">${property.address}</p>` : '<div style="margin-bottom:24px;"></div>'}

          ${score != null ? `
          <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
            <tr><td style="background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.1);border-radius:10px;padding:20px;text-align:center;">
              <p style="margin:0 0 4px;color:#9ca3af;font-size:13px;">Overall Quality Score</p>
              <p style="margin:0;font-size:48px;font-weight:700;color:${scoreColor};">${score}%</p>
            </td></tr>
          </table>` : ''}

          <p style="margin:0 0 24px;color:#d1d5db;font-size:15px;line-height:1.6;">
            Your latest cleaning inspection has been completed and a full quality report is ready for your review.
          </p>

          <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
            <tr><td align="center">
              <a href="${reportUrl}" style="display:inline-block;background:#3b82f6;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;padding:14px 32px;border-radius:8px;">
                View Full Report
              </a>
            </td></tr>
          </table>

          <p style="margin:0;color:#6b7280;font-size:13px;line-height:1.5;">
            This report includes photos, a detailed checklist, and AI-generated quality notes. The link above will always show the latest version of this report.
          </p>

        </td></tr>

        <!-- Footer -->
        <tr><td style="background:#0f1117;border-radius:0 0 12px 12px;border:1px solid rgba(255,255,255,0.1);border-top:none;padding:20px 32px;text-align:center;">
          <p style="margin:0;color:#4b5563;font-size:12px;">Report generated by <strong style="color:#6b7280;">CleanCheck</strong> · <a href="${process.env.NEXT_PUBLIC_APP_URL}" style="color:#6b7280;">cleancheck.io</a></p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'CleanCheck <josh@cleancheck.io>',
      to: property.client_email,
      subject: `Cleaning inspection report — ${property.name}`,
      html,
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    console.error('Resend error:', err)
    return Response.json({ error: 'Failed to send email' }, { status: 500 })
  }

  return Response.json({ success: true })
}
